name: Create Write.as blog post from created issue
on: issues
  types: [opened]

jobs:
  Create-Blog-Post-From-Issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Publish issue content to blog
        run: |
          python publish.py "${{ github.event.issue.body }}"
